BAM Concept:
Bidirectional Associative Memory (BAM) is a type of associative memory that stores pairs of patterns (input and output) and can recall an associated output given an input or vice versa.

In the code:

The weights (w1, w2, w3, w4) are calculated such that when multiplied by an input pattern, they should yield the corresponding output pattern.
The sigmoid function acts as a thresholding function. If the result of the weighted sum is positive, it outputs 1; otherwise, it outputs -1.

Here's how the BAM concept is applied:

Training:
During training, the weights are calculated using the outer product of input and output patterns. These weights form associations between input and output patterns.

Prediction:
To predict the output pattern given an input pattern, the input pattern is multiplied by the weight matrix. The result is passed through the sigmoid function to obtain the predicted output.
Similarly, to predict the input pattern given an output pattern, the output pattern is multiplied by the weight matrix (transposed). Again, the result is passed through the sigmoid function to obtain the predicted input.

Recall:
BAM recalls the associated pattern based on the given input or output. If an input pattern is given, it recalls the associated output pattern, and if an output pattern is given, it recalls the associated input pattern.

In short, BAM can store and retrieve associations between input and output patterns bidirectionally. It's a useful model for pattern recognition, associative recall, and error correction

In [1]:
import numpy as np
# Input Patterns
x1 = np.array([1,-1,1,-1,1,-1]).reshape(6,1)
x2 = np.array([1,-1,1,1,-1,1]).reshape(6,1)
x3 = np.array([-1,-1,-1,-1,-1,-1]).reshape(6,1)
x4 = np.array([1,1,-1,1,1,-1]).reshape(6,1)

# Output Patterns
y1 = np.array([1,-1,1]).reshape(3,1)
y2 = np.array([1,-1,1]).reshape(3,1)
y3 = np.array([-1,-1,-1]).reshape(3,1)
y4 = np.array([1,1,-1]).reshape(3,1)





# Calculating weights
w1 = y1@x1.T
w2 = y2@x2.T
w3 = y3@x3.T
w4 = y4@x4.T

print("Weight1: \n",w1)
print("Weight2: \n",w2)
print("Weight3: \n",w3)
print("Weight4: \n",w4)





def sigmoid(weight):
    temp = []
    for i in weight:
        if i > 0:
            temp.append(1)
        else:
            temp.append(-1)
    return temp

# Output Predicted
Ym1 = sigmoid(w1@x1)
print(Ym1)
Ym2 = sigmoid(w2@x2)
print(Ym2)
Ym3 = sigmoid(w3@x3)
print(Ym3)
Ym4 = sigmoid(w4@x4)
print(Ym4)





# Input from Predicted Output
Xm1 = sigmoid(Ym1@w1)
print(Xm1)
Xm2 = sigmoid(Ym2@w2)
print(Xm2)
Xm3 = sigmoid(Ym3@w3)
print(Xm3)
Xm4 = sigmoid(Ym4@w4)
print(Xm4)

Weight1: 
 [[ 1 -1  1 -1  1 -1]
 [-1  1 -1  1 -1  1]
 [ 1 -1  1 -1  1 -1]]
Weight2: 
 [[ 1 -1  1  1 -1  1]
 [-1  1 -1 -1  1 -1]
 [ 1 -1  1  1 -1  1]]
Weight3: 
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Weight4: 
 [[ 1  1 -1  1  1 -1]
 [ 1  1 -1  1  1 -1]
 [-1 -1  1 -1 -1  1]]
[1, -1, 1]
[1, -1, 1]
[-1, -1, -1]
[1, 1, -1]
[1, -1, 1, -1, 1, -1]
[1, -1, 1, 1, -1, 1]
[-1, -1, -1, -1, -1, -1]
[1, 1, -1, 1, 1, -1]
